name: Test

on:
  workflow_call:
    outputs:
      typecheck:
        description: "Typecheck"
        value: ${{ jobs.typecheck.result }}
      biome:
        description: "Biome"
        value: ${{ jobs.biome.result }}
      test:
        description: "Bun tests"
        value: ${{ jobs.bun-tests.result }}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: bun run typecheck

  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Biome
        run: bun run biome

  bun-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        env:
          NODE_ENV: test
          PORT: 8080
          ORIGIN: http://localhost:3000
          SIGNATURE: this-is-a-test-signature
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: test_db
          RESEND_API_KEY: fake_key
          EMAIL_FROM: fake@example.com
        run: bun run test 